services:
  - type: web
    name: etl-pipeline
    runtime: python
    buildCommand: "pip install --upgrade pip setuptools==69.0.0 wheel && pip install -r requirements.txt"
    startCommand: python app.py
    envVars:
     - key: PYTHON_VERSION
       value: 3.11.9
     - key: PYTHONPATH
       value: /opt/render/project/src
